# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ldt < Formula
  desc "Interactive no-code terminal CLI for the Longitudinal Depression Trajectories toolkit."
  homepage "https://github.com/Longitudinal-Depression-Toolkit/ldt-toolkit"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.3/ldt_0.0.3_darwin_amd64.tar.gz"
      sha256 "83e7862fa76473c887994254b73096ce77abf0e9126cffdbd4f5d65069ed2277"

      define_method(:install) do
        bin.install "ldt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.3/ldt_0.0.3_darwin_arm64.tar.gz"
      sha256 "bf4c98b3c10595c37b39039d83fe8bef58706fc145bb75bdfc925179db0e9e72"

      define_method(:install) do
        bin.install "ldt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.3/ldt_0.0.3_linux_amd64.tar.gz"
      sha256 "ea5eb44bc948de04a115ca04b6a9f3a3cc6c7108e51af0deed02a76000ce2761"
      define_method(:install) do
        bin.install "ldt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.3/ldt_0.0.3_linux_arm64.tar.gz"
      sha256 "2d6b9f2103df7f3ecb810c1c64132ec763b21b275f78248626f4453b4271fc6b"
      define_method(:install) do
        bin.install "ldt"
      end
    end
  end

  test do
    output = shell_output("#{bin}/ldt --help", 1)
    assert_match "interactive mode only", output
  end
end
