# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ldt < Formula
  desc "Interactive no-code terminal CLI for the Longitudinal Depression Trajectories toolkit."
  homepage "https://github.com/Longitudinal-Depression-Toolkit/ldt-toolkit"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.5/ldt_0.0.5_darwin_amd64.tar.gz"
      sha256 "6e3fb1a354c9be047f3af66f593087ed8b3df15bd66f08d88c3ad6a61e850f76"

      define_method(:install) do
        bin.install "ldt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.5/ldt_0.0.5_darwin_arm64.tar.gz"
      sha256 "0efb74636b4da8a9194c44bb4616d04810ecbf03d771f09614e3456b412ec400"

      define_method(:install) do
        bin.install "ldt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.5/ldt_0.0.5_linux_amd64.tar.gz"
      sha256 "f4f9732446ab727bd5e14356a8695b7c0785a4ce883db04916be282451509430"
      define_method(:install) do
        bin.install "ldt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.5/ldt_0.0.5_linux_arm64.tar.gz"
      sha256 "fb2fbcad871579c1df9b8ad18d18c0b43860ecc588a69199ec5a4ba6dc144cdb"
      define_method(:install) do
        bin.install "ldt"
      end
    end
  end

  test do
    output = shell_output("#{bin}/ldt --help", 1)
    assert_match "interactive mode only", output
  end
end
