# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ldt < Formula
  desc "Interactive no-code terminal CLI for the Longitudinal Depression Trajectories toolkit."
  homepage "https://github.com/Longitudinal-Depression-Toolkit/ldt-toolkit"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.7/ldt_0.0.7_darwin_amd64.tar.gz"
      sha256 "ef7be03cac79d776b690df26b5bfd48bb26c8f9a7276e4f8f6371bee83da0a98"

      define_method(:install) do
        bin.install "ldt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.7/ldt_0.0.7_darwin_arm64.tar.gz"
      sha256 "22e77a919427aba1fb5c0ed97adbc84d6d3bc21e57ec7bc994dcf770dde77eb1"

      define_method(:install) do
        bin.install "ldt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.7/ldt_0.0.7_linux_amd64.tar.gz"
      sha256 "710aafacdc395293a96dda617e78aacda1fb14e83cfe56f36433200e0e7542a1"
      define_method(:install) do
        bin.install "ldt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Longitudinal-Depression-Toolkit/CLI/releases/download/v0.0.7/ldt_0.0.7_linux_arm64.tar.gz"
      sha256 "5b50f9ee9f4af2f49370c6dd27d7f0bb5c0568bbfc486b2072cdbfba994a78ac"
      define_method(:install) do
        bin.install "ldt"
      end
    end
  end

  test do
    output = shell_output("#{bin}/ldt --help", 1)
    assert_match "interactive mode only", output
  end
end
